# Generated by Django 2.1.5 on 2019-01-24 18:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='upd_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 24, 18, 55, 13, 719326, tzinfo=utc), verbose_name='date updated'),
            preserve_default=False,
        ),
    ]
