# Generated by Django 2.1.5 on 2019-02-05 14:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_auto_20190125_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 14, 39, 7, 63880, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='todo',
            name='upd_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 14, 39, 7, 63912, tzinfo=utc)),
        ),
    ]
