# Generated by Django 2.1.5 on 2019-02-05 14:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_auto_20190205_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='upd_date',
        ),
        migrations.AddField(
            model_name='todo',
            name='publish_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 14, 39, 51, 434580, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='todo',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 14, 39, 51, 434624, tzinfo=utc)),
        ),
    ]
